test with custom conda environment
For testing, I really want a dedicated virtual environment.  Avoid requirements conflicts that way.  BUT, there is no PyQt5 conda package that matches requirements (yet):

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pyqt5[version='>=5.8']

Current channels:

  - https://conda.anaconda.org/lightsource2-tag/linux-64
  - https://conda.anaconda.org/lightsource2-tag/noarch
  - https://conda.anaconda.org/prjemian/linux-64
  - https://conda.anaconda.org/prjemian/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/aps-anl-tag/linux-64
  - https://conda.anaconda.org/aps-anl-tag/noarch
  - https://conda.anaconda.org/aps-anl-dev/linux-64
  - https://conda.anaconda.org/aps-anl-dev/noarch
```

Can requirement be relaxed to fit what is [available](https://anaconda.org/search?q=pyqt5)?  Looks as if [pyqt5 5.6](https://anaconda.org/inso/pyqt5) is latest for linux-x86_64.  PyPI has [5.13](https://pypi.org/project/PyQt5/) today.